### ISSUE TITLE
Move from Travis CI to Github Actions (blocked by Ruby < 2.1 support)

### ISSUE THREAD

**Issue by ms-ati** [ms-ati/docile#60]
With experience of both, I've found maintenance of CI in Github Actions quite a bit easier than in Travis CI.

Therefore, when the day arrives that we support only Rubies supported in Github Actions, I'd like to plan to transition.

### Checklist

- [x] Add Github Actions CI configuration, in parallel with current Travis CI
- [x] ~(blocked on Ruby versions supported)~ Remove configuration for Travis CI

**Comment by ms-ati** [comment]
See #58.

If no significant requests for support of Docile on EOL (< 2.5) Ruby versions by **Feb 1, 2021**, the plan is to drop all support for EOL versions. At that point, the move from Travis CI to Github Actions would become unblocked.

**Comment by colszowka** [comment]
I believe since Ruby 2.1 has been out of maintenance for quite some time at this point (even [2.4 has been dead for a year](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/)) it should be fine to just drop support. Also, GitHub have deprecated their own setup ruby action in favor of https://github.com/ruby/setup-ruby#supported-versions which actually still supports 2.1.9 if you still want to run CI against it, but honestly I think it's in the best interest of any library users to just drop support for ruby versions that are not receiving security updates any more and force them to update anyway

**Comment by ms-ati** [comment]
@colszowka agreed! There's been no other response here, so I am planning to drop support for < 2.5, and move CI to Github Actions.

**Comment by ms-ati** [comment]
UPDATE: Support for all EOL Rubies (which now means < 2.6) dropped in #65
